[plugins.zlua]
github = "skywind3000/z.lua"

# [plugins.neovide]
# github = "Kethku/neovide"

# [plugins.alien]
# github = "eendroroy/alien"

[plugins.web-search]
github = "sinetoami/web-search"

[plugins.syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.completions]
github = "zsh-users/zsh-completions"

[plugins.history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.autopair]
github = "hlissner/zsh-autopair"

[plugins.almostontop]
github = "Valiev/almostontop"

[plugins.p10k]
github = "romkatv/powerlevel10k"
use = ["powerlevel10k.zsh-theme"]

[plugins.calculator]
github = "arzzen/calc.plugin.zsh"

# [plugins.diffsofancy]
# github = "zdharma/zsh-diff-so-fancy"

[plugins.zsh-vim-mode]
github = "softmoth/zsh-vim-mode"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

# [plugins.scm_breeze]
# github = "scmbreeze/scm_breeze"
# use = ["install.sh"]
