#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # Theme
    colorscheme = "nord"
    colorscheme_bg = "dark"

    default_indent = 8
    max_column = 90
    enable_guicolors = 1
    enable_neomake = 0
    snippet_engine = "ultisnips"
    statusline_separator = "curve"
    statusline_unicode_symbols = 1
    filetree_direction = "left"
    auto_disable_touchpad = 1
    disabled_plugins = ["fzf"]
    # search_tools = "rg"

    # Guide buffer
    # timeoutlen = 100

    # Disable guicolors in basic mode, many terminal do not support 24bit true colors
    enable_guicolors = 1

    # Disable statusline separator, if you want to use other value, please install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = 0
    statusline_left_sections = [
       'winnr',
       'version control info',
       'filename',
       'search index'
    ]
    statusline_right_sections = [
       'syntax checking',
       'cursorpos',
       'percentage',
       'time'
    ]
    warning_symbol = '?'
    error_symbol = '!'

    # file tree manager
    filemanager = "nerdtree"

    # Checkers options
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true

# Enable autocomplete layer
[[layers]]
  name = "core"
  filetree_show_hidden = true

[[layers]]
  name = "autocomplete"
  autocomplete_method = "deoplete"
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "shell"
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "lang#go"

[[layers]]
  name = "tmux"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "VersionControl"
  enable-gtm-status = true

[[layers]]
  name = "checkers"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

# [[layers]]
  # name = "fzf"

[[layers]]
  name = "ctrlspace"
  enable-spacevim-styled-keys = true

# Currently formatter is working without this layer
# [[layers]]
  # name = "format"

[[layers]]
  name = "lsp"
  filetypes = ["go"]
  [layers.override_cmd]
    go = ["gopls"]

[[custom_plugins]]
  name = "RRethy/vim-illuminate"
  merged = false
