# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'

[plugins.zsh-vi-mode]
github = 'jeffreytse/zsh-vi-mode'

[plugins.fast-syntax-highlighting]
github = 'zdharma/fast-syntax-highlighting'

[plugins.zsh-autopair]
github = 'hlissner/zsh-autopair'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.zsh-expand]
github = 'MenkeTechnologies/zsh-expand'

[plugins.calc]
github = 'arzzen/calc.plugin.zsh'

[plugins.zsh-saneopt]
github = 'willghatch/zsh-saneopt'

[plugins.zsh-you-should-use]
github = 'MichaelAquilina/zsh-you-should-use'
