return function()
    -- LSP
    vim.cmd("command! LspAddToWorkspaceFolder lua require(\"fn\").add_to_workspace_folder()")
    vim.cmd("command! LspRemoveWorkspaceFolder lua require(\"fn\").remove_workspace_folder()")
    vim.cmd("command! LspListWorkspaceFolders lua require(\"fn\").list_workspace_folders()")
    vim.cmd("command! LspDocumentSymbol lua require(\"fn\").document_symbol()")
    vim.cmd("command! LspWorkspaceSymbol lua require(\"fn\").workspace_symbol()")
    vim.cmd("command! LspReferences lua require(\"fn\").references()")
    vim.cmd("command! LspClearReferences lua require(\"fn\").clear_references()")
    vim.cmd("command! LspCodeAction lua require(\"fn\").code_action()")
    vim.cmd("command! LspRangeCodeAction lua require(\"fn\").range_code_action()")
    vim.cmd("command! LspDeclaration lua require(\"fn\").declaration()")
    -- vim.cmd('command! LspDefinition lua require("fn").definition()')
    vim.cmd("command! LspTypeDefinition lua require(\"fn\").type_definition()")
    vim.cmd("command! LspDocumentHighlight lua require(\"fn\").document_highlight()")
    vim.cmd("command! LspImplementation lua require(\"fn\").implementation()")
    vim.cmd("command! LspIncomingCalls lua require(\"fn\").incoming_calls()")
    vim.cmd("command! LspOutgoingCalls lua require(\"fn\").outgoing_calls()")
    -- vim.cmd('command! LspFormatting lua require("fn").formatting()')
    -- vim.cmd('command! LspRangeFormatting lua require("fn").range_formatting()')
    -- vim.cmd('command! LspFormattingSync lua require("fn").formatting_sync()')
    vim.cmd("command! LspHover lua require(\"fn\").hover()")
    vim.cmd("command! LspRename lua require(\"fn\").rename()")
    vim.cmd("command! LspSignatureHelp lua require(\"fn\").signature_help()")
    -- Diagnostic
    vim.cmd("command! LspGetAll lua require(\"fn\").get_all()")
    vim.cmd("command! LspGetNext lua require(\"fn\").get_next()")
    vim.cmd("command! LspGetPrev lua require(\"fn\").get_prev()")
    -- vim.cmd('command! LspGoToNext lua require("fn").goto_next()')
    -- vim.cmd('command! LspGoToPrev lua require("fn").goto_prev()')
    vim.cmd("command! LspShowLineDiagnostics lua require(\"fn\").show_line_diagnostics()")
    vim.cmd("command! LspVirtualTextShow lua require(\"fn\").virtual_text_show()")
    vim.cmd("command! LspVirtualTextHide lua require(\"fn\").virtual_text_hide()")
    -- DAP
    --[[ vim.cmd("command! DapToggleBreakpoint lua require(\"dap\").toggle_breakpoint()")
    vim.cmd("command! DapStart lua require(\"dap\").continue()")
    vim.cmd("command! DapContinue lua require(\"dap\").continue()")
    vim.cmd("command! DapStop lua require(\"dap\").stop()")
    vim.cmd("command! DapRestart lua require(\"dap\").restart()")
    vim.cmd("command! DapPause lua require(\"dap\").pause()")
    vim.cmd("command! DapStepOver lua require(\"dap\").step_over()")
    vim.cmd("command! DapStepOut lua require(\"dap\").step_out()")
    vim.cmd("command! DapStepInto lua require(\"dap\").step_into()")
    vim.cmd("command! DapToggleRepl lua require(\"dap\").repl.toggle()")
    vim.cmd("command! DapGetSession lua require(\"dap\").session()") ]]
    -- GIT signs
    vim.cmd("command! GitPreviewHunk lua require(\"fn\").preview_hunk()")
    vim.cmd("command! GitNextHunk lua require(\"fn\").next_hunk()")
    vim.cmd("command! GitPrevHunk lua require(\"fn\").prev_hunk()")
    vim.cmd("command! GitStageHunk lua require(\"fn\").stage_hunk()")
    vim.cmd("command! GitUndoStageHunk lua require(\"fn\").undo_stage_hunk()")
    vim.cmd("command! GitResetHunk lua require(\"fn\").reset_hunk()")
    vim.cmd("command! GitResetBuffer lua require(\"fn\").reset_buffer()")
    vim.cmd("command! GitBlameLine lua require(\"fn\").blame_line()")
    -- Symbols outline
    vim.cmd("command! SymbolsOutline lua require(\"symbols-outline\").toggle_outline()")
    -- Set path
    vim.cmd("command! SetGlobalPath lua require(\"fn\").set_global_path()")
    vim.cmd("command! SetWindowPath lua require(\"fn\").set_window_path()")
    -- Init vimspector
    -- vim.cmd('command! VimspectorInit lua require("configs.global.debugers").init_vimspector()')
    -- Init Dap
    -- vim.cmd("command! DapInit lua require(\"configs.global.debugers\").init_dap()")
end
